/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package computer.user.kiosTembakau;

/**
 *
 * @author user
 */
public class TobaccoForm extends javax.swing.JFrame {

    /**
     * Creates new form aaaetn
     */
    private static javax.swing.table.DefaultTableModel tobaccoTableModel = new javax.swing.table.DefaultTableModel(
        new Object[][]{
            {"Barack Taste 50g (semua rasa)", 1.4, 18000},
            {"Queen Bee 50g", 2,  15000},
            {"Virginia Original 50g", 2.5,  15000},
            {"Captain Black 50g", 3,  150000}
        },
        new String[]{"Nama Produk", "Nikotin (mg) (per 700mg)", "Harga Produk"}
    ) {
        Class[] types = new Class[]{
            java.lang.String.class, java.lang.Double.class, java.lang.Double.class
        };

        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }
    };
    
    public TobaccoForm() {
        initComponents();
        tobaccoTable.setModel(tobaccoTableModel);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        nicotineField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tobaccoTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        productMenu = new javax.swing.JMenu();
        productMenuTobacco = new javax.swing.JMenuItem();
        productMenuRoller = new javax.swing.JMenuItem();
        productMenuPaper = new javax.swing.JMenuItem();
        productMenuFilter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        nicotineField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicotineFieldActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Harga Produk: ");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nama Produk:");

        jLabel3.setBackground(new java.awt.Color(255, 153, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 69, 53));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manajemen Produk Tembakau");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Masukkan value, lalu tekan 'Tambah Produk' untuk menambahkan.");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Pilih produk dan masukkan value yang baru, lalu tekan 'Update Produk' untuk mengedit.");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        addButton.setBackground(new java.awt.Color(204, 255, 153));
        addButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        addButton.setText("Tambah Produk");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(255, 255, 153));
        updateButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        updateButton.setText("Update Produk");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 102, 102));
        deleteButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deleteButton.setText("Hapus Produk");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(updateButton)
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Kadar Nikotin:");

        tobaccoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Produk", "Kadar Nikotin", "Harga Produk"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tobaccoTable.setGridColor(new java.awt.Color(102, 102, 102));
        tobaccoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tobaccoTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tobaccoTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicotineField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nicotineField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        productMenu.setText("Lihat Produk");

        productMenuTobacco.setText("Tembakau");
        productMenuTobacco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMenuTobaccoActionPerformed(evt);
            }
        });
        productMenu.add(productMenuTobacco);

        productMenuRoller.setText("Alat Linting");
        productMenuRoller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMenuRollerActionPerformed(evt);
            }
        });
        productMenu.add(productMenuRoller);

        productMenuPaper.setText("Kertas");
        productMenuPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMenuPaperActionPerformed(evt);
            }
        });
        productMenu.add(productMenuPaper);

        productMenuFilter.setText("Filter");
        productMenuFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMenuFilterActionPerformed(evt);
            }
        });
        productMenu.add(productMenuFilter);

        jMenuBar1.add(productMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void nicotineFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicotineFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicotineFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        addProduct();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        updateProduct();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        deleteProduct();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void tobaccoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tobaccoTableMouseClicked
        // TODO add your handling code here:
        int selectedIndex = tobaccoTable.getSelectedRow();
        if (selectedIndex != -1) {
            String name = tobaccoTableModel.getValueAt(selectedIndex, 0).toString();
            String type = tobaccoTableModel.getValueAt(selectedIndex, 1).toString();
            String price = tobaccoTableModel.getValueAt(selectedIndex, 2).toString();

            nameField.setText(name);
            priceField.setText(price);
            nicotineField.setText(type);
        }
    }//GEN-LAST:event_tobaccoTableMouseClicked

    private void productMenuTobaccoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMenuTobaccoActionPerformed
        // TODO add your handling code here:
        TobaccoForm tobaccoForm = new TobaccoForm();
        tobaccoForm.setVisible(true);
        tobaccoForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_productMenuTobaccoActionPerformed

    private void productMenuRollerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMenuRollerActionPerformed
        // TODO add your handling code here:
        RollerForm rollerForm = new RollerForm();
        rollerForm.setVisible(true);
        rollerForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_productMenuRollerActionPerformed

    private void productMenuPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMenuPaperActionPerformed
        // TODO add your handling code here:
        PaperForm paperForm = new PaperForm();
        paperForm.setVisible(true);
        paperForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_productMenuPaperActionPerformed

    private void productMenuFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMenuFilterActionPerformed
        // TODO add your handling code here:
        FilterForm filterForm = new FilterForm();
        filterForm.setVisible(true);
        filterForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_productMenuFilterActionPerformed

    private void addProduct() {
        String name = nameField.getText();
        double price = Double.parseDouble(priceField.getText());
        double nicotineContent = Double.parseDouble(nicotineField.getText());
        
        Tobacco newProduct = new Tobacco(name, price, nicotineContent);

        tobaccoTableModel.addRow(new Object[]{newProduct.getName(), newProduct.getNicotineContent(), newProduct.getPrice()});

        clearFields();
    }

    private void updateProduct() {
        int selectedIndex = tobaccoTable.getSelectedRow();
        if (selectedIndex != -1) {
            String name = nameField.getText();
            double price = Double.parseDouble(priceField.getText());
            double nicotineContent = Double.parseDouble(nicotineField.getText());

            // Perbarui produk di tabel
            tobaccoTableModel.setValueAt(name, selectedIndex, 0);
            tobaccoTableModel.setValueAt(nicotineContent, selectedIndex, 1);
            tobaccoTableModel.setValueAt(price, selectedIndex, 2);

            clearFields();
        }
    }
    
    private void deleteProduct() {
        int selectedIndex = tobaccoTable.getSelectedRow();
        if (selectedIndex != -1) {
            tobaccoTableModel.removeRow(selectedIndex);

            clearFields();
        }
    }
    
    private void clearFields() {
        nameField.setText("");
        priceField.setText("");
        nicotineField.setText("");
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TobaccoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TobaccoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TobaccoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TobaccoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TobaccoForm tobaccoForm = new TobaccoForm();
                tobaccoForm.setLocationRelativeTo(null);
                tobaccoForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nicotineField;
    private javax.swing.JTextField priceField;
    private javax.swing.JMenu productMenu;
    private javax.swing.JMenuItem productMenuFilter;
    private javax.swing.JMenuItem productMenuPaper;
    private javax.swing.JMenuItem productMenuRoller;
    private javax.swing.JMenuItem productMenuTobacco;
    private javax.swing.JTable tobaccoTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
